### ISSUE TITLE
AttributeError: 'DiffusionEngine' object has no attribute 'network_layer_mapping'

### ISSUE THREAD

**Issue by matrix4767** [v0xie/sd-webui-incantations#12]
Got this error as soon as I installed the extension, and also every time I generate something, even if none of the features are enabled. Of course, they do not work if enabled either.

*** Error running postprocess_batch: G:\webui_forge_cu121_torch21\webui\extensions\sd-webui-incantations\scripts\incantation_base.py
    Traceback (most recent call last):
      File "G:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 851, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "G:\webui_forge_cu121_torch21\webui\extensions\sd-webui-incantations\scripts\incantation_base.py", line 91, in postprocess_batch
        m.module.postprocess_batch(p, *self.m_args(m, *args), **kwargs)
      File "G:\webui_forge_cu121_torch21\webui\extensions\sd-webui-incantations\scripts\t2i_zero.py", line 213, in postprocess_batch
        self.t2i0_postprocess_batch(p, *args, **kwargs)
      File "G:\webui_forge_cu121_torch21\webui\extensions\sd-webui-incantations\scripts\t2i_zero.py", line 216, in t2i0_postprocess_batch
        self.unhook_callbacks()
      File "G:\webui_forge_cu121_torch21\webui\extensions\sd-webui-incantations\scripts\t2i_zero.py", line 224, in unhook_callbacks
        cross_attn_modules = self.get_cross_attn_modules()
      File "G:\webui_forge_cu121_torch21\webui\extensions\sd-webui-incantations\scripts\t2i_zero.py", line 408, in get_cross_attn_modules
        nlm = m.network_layer_mapping
      File "G:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'DiffusionEngine' object has no attribute 'network_layer_mapping'

**Comment by v0xie** [comment]
Thanks, I'll add a note that the extension is currently incompatible with Forge

**Comment by slashedstar** [comment]
> Thanks, I'll add a note that the extension is currently incompatible with Forge

Do you have plans to make it compatible with forge?
