### ISSUE TITLE
'CFGDenoiserParams' object has no attribute 'denoiser'

### ISSUE THREAD

**Issue by Miczu** [v0xie/sd-webui-incantations#14]
Got those errors for each step when running "Perturbed Attention Guidance". Just got this extension installed, so can't say it worked for me before...
Breaks for both SD15 and SDXL models.
I disabled all optional extensions in text2img, but if this can't be reproduced, I can attempt to disable other installed extensions (though that's a bit of a pain).

> 
> 0%|                                                                                           | 0/24 [00:00<?, ?it/s]*** Error executing callback cfg_denoiser_callback for M:\ML\1111\stable-diffusion-webui\extensions\_sd-webui-incantations\scripts\pag.py
>     Traceback (most recent call last):
>       File "M:\ML\1111\stable-diffusion-webui\modules\script_callbacks.py", line 216, in cfg_denoiser_callback
>         c.callback(params)
>       File "M:\ML\1111\stable-diffusion-webui\extensions\_sd-webui-incantations\scripts\pag.py", line 141, in <lambda>
>         cfg_denoise_lambda = lambda callback_params: self.on_cfg_denoiser_callback(callback_params, pag_params)
>       File "M:\ML\1111\stable-diffusion-webui\extensions\_sd-webui-incantations\scripts\pag.py", line 278, in on_cfg_denoiser_callback
>         pag_params.denoiser = params.denoiser
>     AttributeError: 'CFGDenoiserParams' object has no attribute 'denoiser'
> 
> ---
> *** Error executing callback cfg_denoised_callback for M:\ML\1111\stable-diffusion-webui\extensions\_sd-webui-incantations\scripts\pag.py
>     Traceback (most recent call last):
>       File "M:\ML\1111\stable-diffusion-webui\modules\script_callbacks.py", line 224, in cfg_denoised_callback
>         c.callback(params)
>       File "M:\ML\1111\stable-diffusion-webui\extensions\_sd-webui-incantations\scripts\pag.py", line 142, in <lambda>
>         cfg_denoised_lambda = lambda callback_params: self.on_cfg_denoised_callback(callback_params, pag_params)
>       File "M:\ML\1111\stable-diffusion-webui\extensions\_sd-webui-incantations\scripts\pag.py", line 331, in on_cfg_denoised_callback
>         cond_in = catenate_conds([tensor, uncond])
>       File "M:\ML\1111\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 13, in catenate_conds
>         return torch.cat(conds)
>     TypeError: expected Tensor as element 0 in argument 0, but got NoneType
> 
> ---
>   4%|███▍                                                                               | 1/24 [00:00<00:19,  1.20it/s]*** Error executing.....

Let me know if there is anything I can help with testing.

**Comment by Miczu** [comment]
I'm testing other features and "Multi-Concept T2I-Zero" appears to work (differences in images) and without exceptions.

**Comment by ribawaja** [comment]
Also getting same error.

AttributeError: 'CFGDenoiserParams' object has no attribute 'denoiser'

Using A1111 1.6.0.
Don't think I have any other extensions which would modify the CFGDenoiser.

**Comment by ribawaja** [comment]
Updated to latest A1111 (1.9.3), and the problem went away. So, potentially a compatibility problem with older versions.

**Comment by Koitenshin** [comment]
I'm on A1111 v1.9.3 and getting this error. The extension runs all the time even when none of the features are enabled. It broke everything until I fully disabled the extension. "The size of tensor A must match the size of Tensor B at non-singleton dimension 3" would not let me generate at all until I removed the extension.
