### ISSUE TITLE
Issue at install (Transformers?)

### ISSUE THREAD

**Issue by Derjyn** [v0xie/sd-webui-incantations#6]
I was really excited to dive into yet another of your awesome offerings... However, running into an issue after install. System and SD WebUI details:

**_System_**
OS: Windows 10
CPU: Intel i7
GPU: Nvidia RTX 3070

**_SD WebUI_**
Version: 1.7.0
Python: 3.11.8
Torch: 2.2.0+cu121
xformers: N/A
Gradio: 3.41.2

**_Traceback_**
```
incant.py: done in 0.021s
*** Error loading script: incantation_base.py
    Traceback (most recent call last):
      File "D:\AIA\Tools\SDUI\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\AIA\Tools\SDUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AIA\Tools\SDUI\extensions\sd-webui-incantations\scripts\incantation_base.py", line 13, in <module>
        from scripts.p2hp import P2HP
      File "D:\AIA\Tools\SDUI\extensions\sd-webui-incantations\scripts\p2hp.py", line 8, in <module>
        from scripts.prompt_optim_utils import optimize_prompt
      File "D:\AIA\Tools\SDUI\extensions\sd-webui-incantations\scripts\prompt_optim_utils.py", line 32, in <module>
        from sentence_transformers.util import (semantic_search,
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
        from .datasets import SentencesDataset, ParallelSentencesDataset
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\datasets\__init__.py", line 1, in <module>
        from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\datasets\DenoisingAutoEncoderDataset.py", line 5, in <module>
        from transformers.utils.import_utils import is_nltk_available, NLTK_IMPORT_ERROR
    ImportError: cannot import name 'is_nltk_available' from 'transformers.utils.import_utils' (D:\AIA\Tools\SDUI\venv\Lib\site-packages\transformers\utils\import_utils.py)

---
  incantation_base.py: done in 0.057s
*** Error loading script: p2hp.py
    Traceback (most recent call last):
      File "D:\AIA\Tools\SDUI\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\AIA\Tools\SDUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AIA\Tools\SDUI\extensions\sd-webui-incantations\scripts\p2hp.py", line 8, in <module>
        from scripts.prompt_optim_utils import optimize_prompt
      File "D:\AIA\Tools\SDUI\extensions\sd-webui-incantations\scripts\prompt_optim_utils.py", line 32, in <module>
        from sentence_transformers.util import (semantic_search,
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
        from .datasets import SentencesDataset, ParallelSentencesDataset
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\datasets\__init__.py", line 1, in <module>
        from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\datasets\DenoisingAutoEncoderDataset.py", line 5, in <module>
        from transformers.utils.import_utils import is_nltk_available, NLTK_IMPORT_ERROR
    ImportError: cannot import name 'is_nltk_available' from 'transformers.utils.import_utils' (D:\AIA\Tools\SDUI\venv\Lib\site-packages\transformers\utils\import_utils.py)

---
  p2hp.py: done in 0.012s
*** Error loading script: prompt_optim_utils.py
    Traceback (most recent call last):
      File "D:\AIA\Tools\SDUI\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\AIA\Tools\SDUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AIA\Tools\SDUI\extensions\sd-webui-incantations\scripts\prompt_optim_utils.py", line 32, in <module>
        from sentence_transformers.util import (semantic_search,
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
        from .datasets import SentencesDataset, ParallelSentencesDataset
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\datasets\__init__.py", line 1, in <module>
        from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
      File "D:\AIA\Tools\SDUI\venv\Lib\site-packages\sentence_transformers\datasets\DenoisingAutoEncoderDataset.py", line 5, in <module>
        from transformers.utils.import_utils import is_nltk_available, NLTK_IMPORT_ERROR
    ImportError: cannot import name 'is_nltk_available' from 'transformers.utils.import_utils' (D:\AIA\Tools\SDUI\venv\Lib\site-packages\transformers\utils\import_utils.py)
```

**Comment by Derjyn** [comment]
As a potential fix, I hopped into a virtual environment for my SDWUI set up, and did a pip install of the `sentence_transformer` library. The above traceback/error has gone away, but I don't see any hint of Incantations being active - that is, no options, feedback in the console, etc.

**Comment by v0xie** [comment]
Sorry about that. Try `pip install "sentence_transformers>=2.2.2" "transformers==4.30.2"`

**Comment by v0xie** [comment]
We're not using sentence transformers in the main branch so this is not an issue for the time being.
